import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';
import FetchAPI from './API_Proxy';
import data from '../data.json';
import * as Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';

const inter = Inter({ subsets: ['latin'] });

// [ [1, 1] ]

export default function Home() {
    console.log(data);

    function formatDate(date: string): number {
        return new Date(date).getTime(); //might need milliseconds in a day if highcharts doesnt fix day accuracy issue that exists within the new Date function (86,400,000)
    }
    const dailyData = data['Time Series (Daily)']; // {'12/12/1 : {high: 0}}

    // [12/21/21, 12/21/22, ]
    console.log(Object.keys(dailyData));
    const timeSeriesData = Object.keys(dailyData).map((dateKey: string) => {
        return [formatDate(dateKey), Number(dailyData[dateKey]['2. high'])];
    });

    console.log(timeSeriesData);
    
    const options: Highcharts.Options = {
        title: {
            text: `Daily High For IBM`,
        },
        xAxis: {
            type: 'datetime',
        },
        yAxis: {
            title: {
                text: 'Daily High',
            },
        },
        series: [
            {
                type: 'area',
                data: timeSeriesData,
            },
        ],
    };

    // const [stockData, setStockData] = useState([])
    // const [search, setSearch] = useState("")
    // const [searchSubmit, setSearchSubmit] = useState("")
    // //console.log(process.env.NEXT_PUBLIC_API_KEY) `https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=${searchSubmit}&apikey=${process.env.NEXT_PUBLIC_API_KEY}`

    // const handleSymbolSearchSubmit = (e: any) => {
    //   e.preventDefault()
    //   setSearchSubmit(search)
    // }

    // const handleSearchInput = (e: any) => {
    //   setSearch(e.target.value.toUpperCase())
    // }

    // const stocksDataFetch = new FetchAPI(`https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=${searchSubmit}&apikey=${process.env.NEXT_PUBLIC_API_KEY}`)

    // useEffect(()=>{
    //   stocksDataFetch.getFetchRequest()
    //   .then(setStockData)
    // }, [])

    // console.log(stockData)
    // console.log(searchSubmit)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {/* <form onSubmit={handleSymbolSearchSubmit}>
          <input type="text" placeHolder="Search symbol here..." value={search} onChange={handleSearchInput} />
          <input type="submit" value="Submit"/>
        </form> */}
                <HighchartsReact highcharts={Highcharts} options={options} />
            </main>
        </>
    );
}

/*sites to keep in mind:
https://rapidapi.com/alphavantage/api/alpha-vantage
https://www.alphavantage.co/documentation/
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/basic-line/ - Highcharts stock example
https://www.highcharts.com/docs/getting-started/your-first-chart - highcharts docs getting started
https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/usdeur.json - example of how data should look for chart implementation
https://www.highcharts.com/demo/line-time-series - timeseries example chart in JS
https://github.com/highcharts/highcharts-react#highcharts-with-nextjs - github documentation of highcharts with nextjs
*/
